newfile created
lfundaro/testRepo pull request #1
Opened 2017-06-06 22:27 UTC by lfundaro

2017-06-06 22:37 UTC, lfundarotest requested changes
what do you think about making that change ?

2017-06-06 22:37 UTC, lfundarotest commented on newFile.json
> +{}
can we make a change here ?

2017-06-11 14:17 UTC, lfundaro reviewed
this is a comment, not a review

2017-06-11 14:17 UTC, lfundaro commented on newFile.json
> +{}
there is something here we could add.

2017-06-11 14:19 UTC, lfundarotest requested changes
this is a review summary.

2017-06-11 14:19 UTC, lfundarotest commented on newFile.json
> +{}
I would like to rephrase this part.

2017-06-11 14:20 UTC, lfundarotest requested changes
this is the summary of my PR

2017-06-11 14:20 UTC, lfundarotest commented on newFile.json
> +{}
I have yet another comment to make here

2017-06-11 14:25 UTC, lfundarotest approved these changes

2017-06-11 14:27 UTC, merged